#!/bin/sh
nodes="$HOME/backend/address"
counter=-1
file=$(cat $nodes)
for line in $file
do
  case $line in '') ;; *)
    acomment=${line%#*}
    peer="$(echo "${acomment}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    case $peer in '') echo "linha comentada="$line ;; *)
      case $counter in '-1')
        $HOME/backend/ip_hostname $peer root

      ;; *)
        $HOME/backend/ip_hostname $peer peer$counter
      esac
      counter=$((counter+1))
    esac
  esac
done;




