#!/bin/sh
nodes="$HOME/backend/address"
file=$(cat $nodes)
for line in $file
do
  case $line in '') ;; *)
    acomment=${line%#*}
    peer="$(echo "${acomment}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    case $peer in '') echo "linha comentada="$line ;; *)
      $HOME/backend/known_hosts $peer
    esac
  esac
done;




