#!/bin/sh
nodes="/home/ubuntu/backend/address"
counter=0
file=$(cat $nodes)
for line in $file
do
  case $line in '') ;; *)
    acomment=${line%#*}
    slave="$(echo "${acomment}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
    case $slave in '') echo "linha comentada="$line ;; *)
      /home/ubuntu/backend/known_hosts $slave
      counter=$((counter+1))
    esac
  esac
done;




