#!/bin/sh
case $1 in '') echo "IP??" exit ;; *) 
  echo "IP: $1"	
  ssh -oStrictHostKeyChecking=no ubuntu@$1 uptime
  scp -i ~/credential.pem ~/credential.pem ubuntu@$1:/home/ubuntu/.ssh/id_rsa
  #ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
;; esac


